### ISSUE TITLE
Migrate to use PostCSS instead of Sass?

### ISSUE THREAD

**Issue by thomasbritton** [uswitch/ustyle#220]
This would be a pretty big project but just interested in what people thoughts would be 😄

**Comment by Charlotteis** [comment]
First question: Why? 😄

**Comment by annez** [comment]
Why? I don't see the reasoning for this. 

1. What are the benefits?
2. Is there a safe upgrade path?
3. Will it work with older rails projects?

The reason we picked Sass is because most of our front-end is in Ruby, now I am aware we're moving away from this architecture, but that doesn't mean a significant number of our apps don't still use it. I realise that PostCSS is the "future" for Node projects, however until we solve the asset compilation / static pre-compiled assets on Rails without Sprockets, this is a no-go.

https://twitter.com/postcss/status/681795745012396033

**Comment by annez** [comment]
I'm closing this for now until this is more fleshed out.
