### ISSUE TITLE
Content: Form Label Best Practices

### ISSUE THREAD

**Issue by Charlotteis** [uswitch/ustyle#257]
uStyle says:

> For text inputs that are optional, add "(optional)" to the placeholder attribute for the input

However, placeholders aren't seen by everyone so it'd be better to put "(optional)" in the label itself.

It would be good to change this content, and also add something about making sure every input has a label.

Any concerns if we make this change to our guidelines?

**Comment by AgentAntelope** [comment]
Is adding "(optional)" standard practice? I have commonly seen "*" used to annotate the labels of required fields, with no annotation on the label for optional things.

**Comment by Charlotteis** [comment]
> Is adding "(optional)" standard practice? I have commonly seen "*" used to annotate the labels of required fields, with no annotation on the label for optional things.

This is what I am used to, could be worth doing a little research in what smarter folk than I suggest.

**Comment by AgentAntelope** [comment]
https://www.w3.org/TR/WCAG20-TECHS/ARIA2.html seems to say it's standard practice to use "*" alongside `aria-required`

**Comment by Charlotteis** [comment]
from nic

> (optional) for optional fields with the form label (where one exists)….where it doesn’t exist (energy main process phone number) put in placeholder?

**Comment by Charlotteis** [comment]
I believe that fells way is the way to go as it allows us to enforce required fields for screen readers as well. If we can have the same practice for sighted and not-sighted users, this requires less thinking when it comes to building these things.

I know it says "required" can be intimidating, but I trust the W3C to get this right.

**Comment by greenie** [comment]
A historical reason for having "(optional)" in the placeholder was for the Energy homepage where we don't have labels (I know 😢). The placeholder clue for phone number but not email address (which is _actually_ optional) gives us significantly more Insight email signups for a marginally lower continuation rate. I realise that is obviously a terrible reason for doing so and the Energy homepage should absolutely change to be more inline with best practices.

Another reason for not highlighting required fields is that the majority of our form fields tend to be required, and having everything labelled as such makes them look more intimidating. There is an article about how only highlighting optional fields leads to a better completion rate, although I can't find the link to it.

That being said, we should at minimum update the Best Practices section to include the recommendation of adding `aria-required` to required fields.

I think we should have a discussion about highlighting required vs. highlighting optional because at the time we had a good reason to do so and it's worth revisiting whether or not this still applies.

**Comment by Charlotteis** [comment]
I'd like to keep the "make sure you have labels" in, so that's something we can move toward? Does that sound ok?

**Comment by greenie** [comment]
Definitely! Label all the things :)

**Comment by nickfrankcom** [comment]
Another case for float label pattern?

http://bradfrost.com/blog/post/float-label-pattern/

**Comment by Charlotteis** [comment]
Worth discussing!

**Comment by Charlotteis** [comment]
Here is what I've proposed and will be PRing later:

```
//   #### Best practices
//   * All form inputs must have a corresponding label, linked to the input
//   * The label should be visible; placeholders should not be relied on as not every browser can see them, nor can all screenreaders. A visible permanent label provides continuous context
//   * For text inputs that are optional, add "(optional)" to the input label
//   * Add `aria-required` to any input field that must be filled in
//   * See our best practices for [writing form labels](../language/microcopy.html#Form text, form labels)
```

**Comment by Charlotteis** [comment]
I have PR'ed this along with some other additions to uStyle with regards to accessibility. #259
